categories = {
  'Akcja': 28,
  'Animacja': 2,
  'Dokument': 5,
  'Dramat': 6,
  'Familijny': 8,
  'Fantasy': 9,
  'Horror': 12,
  'Komedia': 13,
  'Krótkometrażowy': 50,
  'Kryminalny': 15,
  'Melo-dramat': 16,
  'Niemy': 67,
  'Przygodowy': 20,
  'Romans': 32,
  'Sci-Fi': 33,
  'Thriller': 24,
  'Animacja aktorska': 79,
  'Animacja dla dorosłych': 77,
  'Anime': 66,
  'Basn': 42,
  'Biograficzny': 3,
  'Czarna komedia': 47,
  'Dla dzieci': 4,
  'Dla mlodziezy': 41,
  'Dokumentalizowany': 57,
  'Dramat historyczny': 59,
  'Dramat obyczajowy': 37,
  'Dramat sadowy': 65,
  'Dramat spoleczny': 69,
  'Dreszczowiec': 46,
  'Edukacyjny': 64,
  'Erotyczny': 7,
  'Etiuda': 45,
  'Fikcja literacka': 75,
  'Film Noir': 27,
  'Gangsterski': 53,
  'Groteska filmowa': 60,
  'Historyczny': 11,
  'Karate': 54,
  'Katastroficzny': 40,
  'Komedia dokumentalna': 74,
  'Komedia kryminalna': 58,
  'Komedia obyczajowa': 29,
  'Komedia romantyczna': 30,
  'Kostiumowy': 14,
  'Musical': 17,
  'Muzyczny': 44,
  'Nowele filmowe': 18,
  'Obyczajowy': 19,
  'Poetycki': 62,
  'Polityczny': 43,
  'Prawniczy': 52,
  'Propagandowy': 76,
  'Przyrodniczy': 73,
  'Psychologiczny': 38,
  'Religijny': 51,
  'Satyra': 39,
  'Sensacyjny': 22,
  'Sportowy': 61,
  'Surrealistyczny': 10,
  'Szpiegowski': 63,
  'Sztuki walki': 72,
  'Swiateczny': 78,
  'Western': 25,
  'Wojenny': 26,
}

def get_categories_parsed(category_names):
  invalid_categories = []
  parsed = ''
  for name in category_names:
    try:
      parsed += f'{categories[name]},'
    except:
      invalid_categories.append(name)
  return parsed[:-1]
